### ISSUE TITLE
configもwebブラウザ上で行う場合の案

### ISSUE THREAD

**Issue by sakots** [satopian/poti-kaini#3]
- マスターパスワードだけアップロード前に決めておく。
- 初期設定画面に入る前にマスターパスワードを入力、初期値以外の完全一致でのみ先に進める。

だと、懸念されていた「アップロードしたあと偶然誰かが初期設定をしてしまう」を回避できそうですがどうですか。

パスワードだけのファイルなら短くてすみますし。

**Comment by satopian** [comment]
パスワードが一致して入れれば全設定を変更可能になるのでやりません。
