### ISSUE TITLE
使用ツールをユーザーコードに記録すれば動画がなくてもツールがわかる

### ISSUE THREAD

**Issue by sakots** [satopian/poti-kaini#9]
何年か前に自分がPOTIから外した機能なので…

[https://github.com/sakots/ROIS/releases/tag/v0.99.12](https://github.com/sakots/ROIS/releases/tag/v0.99.12)

ROISに実装してみました。
ログの形式は変わらないのでPOTIでも使えると思います。

**Comment by satopian** [comment]
**描画時間の記録のユーザーコードへの記録は、私が考えて新たに実装した機能です**ので、**拡張ヘッダにどんな情報でもいれる事ができて取り出せる事まではわかっています**。
それから、`picpost.php`を書き直して、その拡張ヘッダの取り出し方法を可変変数からより安全な連想配列に変更したのも私です。
この場合、拡張ヘッダにいれられる、ユーザーデータに記録できるまではわかっている事なのですが、

>ログの形式は変わらないのでPOTIでも使えると思います。

POTI-boardでもログの形式は変わらないのですか?

この返信にも時間をつかっており、もし、ログの拡張が結局必要だったりした場合は、情報をもらっているのではなく、返信の手間がかかっているだけになってしまいます。
POTI-board EVOはログの互換性を維持しながら機能を追加していく方針です。

**Comment by satopian** [comment]
お絵かき掲示板交流サイトのツールの表示は、ログに何も記録されておらず、代わりにpchならNEO、spchならしぃペインター、chiならChickenPaintで判定しています。
コードを覗いてみましたが…。
データベースにツールの種類の記録場所があるわけですね。
`				$sql = "INSERT INTO tablelog (created, modified, name, sub, com, mail, url, picfile, pchfile, img_w, img_h, utime, parent, time, pwd, id, exid, tree, age, invz, host, tool) VALUES (datetime('now', 'localtime'), datetime('now', 'localtime'), '$name', '$sub', '$com', '$mail', '$url', '$picfile', '$pchfile', '$img_w', '$img_h', '$utime', '$parent', '$time', '$pwdh', '$id', '$exid', '$tree', '$age', '$invz', '$host', '$used_tool')";
`
だとすると、ツールの種類を記録する場所がないPOTI-boardではログの拡張が必要になるはずです。

**Comment by satopian** [comment]
カンマの数を増やして拡張して、ログを解析する時は、カンマが余分にある事にして取り出せばとりあえずエラーはでない…。
ただ、そこまでしてツールの種類を表示する必要があるのかないのか…ですね。
現状では、NEOの画風と、ChickenPaintは画面をみればだいたい区別が付くし、しぃペインターは先が無い感じも。
拡張機能としてのCeepjが掲示板で使えなくなってますね。
拡張機能じゃなくて、直接呼び出しのurlを貼り付けているPOTI-boardではなんとか動きますが…。

**Comment by sakots** [comment]
データベースへのツールの記載は、実際に呼び出すのには使ってないですが念の為記録しています。
（ユーザーコードを使わないときには必要だった名残り）
使用ツールを表示したいユーザーさんがいたことと、今後対応ツールが増えることを考えていれてみました。
実際 [8bitPaint](https://minordaimyo.net/) が組み込めそうです

**Comment by sakots** [comment]
CheerpJはロード時間が長すぎて描く気がなくなるのが問題ですね
今しぃペインターNEO作ってますがいつ出来上がるかもわかりませんし、いらないかもしれない。

**Comment by sakots** [comment]
動画ファイル形式で判別するのが一番簡単ですが、
https://github.com/satopian/poti-kaini/issues/10
こういうのがありまして。

**Comment by satopian** [comment]
> 動画ファイル形式で判別するのが一番簡単ですが、

いえ、テキストログに保存するカラムがあれば簡単に実装できます。ただ、ログファイルの拡張が必要になるだけです。
dbはあくまでも使ってないというので、調べようとしましたが、壮大な時間の無駄になりそうなので…。
cheerpjは、POTI-board以外のサイト、BBSNoteそのほかの絵板でChromeの拡張機能を使って動くかどうか試してみると現時点では動作しない(ペイント画面からトップページに戻される)という問題が新たに発生しています。
つい先日更新されたもの。

あと、今回のような提案をされると、ROISの解析まで必要になるし、ログの拡張が必要ないという点の説明もよくわからないので、対応できません。
ROISでいろいろ実現できているのならそれはROISでやってもらえませんか?
ここで書く事では無いと思います。
(特にPOTI-boardのissuesでROISの新機能をアピールされてもこまります)

たとえばこの場合、ログの拡張が必要ではないという根拠が具体的なコードで示されていれば、まだ議論できる範囲だと思います。
拡張ヘッダに使ったツールをセットできるは、実際に他のサイトの絵板ではすでにそうなっているので、私にもわかります。

**Comment by satopian** [comment]
```
			// スレ建ての場合
			if (empty($_POST["modid"]) === true) {
				$age = 0;
				$sql = "INSERT INTO tablelog (created, modified, name, sub, com, mail, url, picfile, pchfile, img_w, img_h, utime, parent, time, pwd, id, exid, tree, age, invz, host, tool) VALUES (datetime('now', 'localtime'), datetime('now', 'localtime'), '$name', '$sub', '$com', '$mail', '$url', '$picfile', '$pchfile', '$img_w', '$img_h', '$utime', '$parent', '$time', '$pwdh', '$id', '$exid', '$tree', '$age', '$invz', '$host', '$used_tool')";

```
処理を追いかけてみましたが、dbに$used_toolとして保存されてますね。
表示側も確認してみましたがdbから読み出しています。
ログの拡張が必要なかったとしたら、それはROISだったからであって、POTIでは、カラムを増やすか、カンマ区切りの中にさらに結合してあとで分離といった処理をしなければならないはずです。
ツールの対応をしたいけれどしなかったのはそれが理由です。
ですが、ログのカラムの拡張も検討してみます。

**Comment by satopian** [comment]
ログの拡張は必要ないと聞いて、だとしたらどこに保存しているのかを調べる手間…。
そんな話をしている時間はないので勘弁してください。
